version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-image .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker tag my-image:latest <account-id>.dkr.ecr.<region>.amazonaws.com/my-image:latest
      - docker push <account-id>.dkr.ecr.<region>.amazonaws.com/my-image:latest

artifacts:
  files:
    - '**/*'
